"""Add permission_resources table

Revision ID: 16816d5fcbf5
Revises: 04c2cc80f725
Create Date: 2026-03-22 14:07:27.623840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16816d5fcbf5'
down_revision = '04c2cc80f725'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_resources_id'), 'permission_resources', ['id'], unique=False)
    op.create_index(op.f('ix_permission_resources_name'), 'permission_resources', ['name'], unique=True)
    op.drop_column('casbin_rule', 'v4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casbin_rule', sa.Column('v4', sa.VARCHAR(length=255, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_permission_resources_name'), table_name='permission_resources')
    op.drop_index(op.f('ix_permission_resources_id'), table_name='permission_resources')
    op.drop_table('permission_resources')
    # ### end Alembic commands ###
