"""Add_soft_delete_to_reservations

Revision ID: 17f8ebfb2b90
Revises: 5965ef8cb48a
Create Date: 2026-03-23 19:27:01.921317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17f8ebfb2b90'
down_revision = '5965ef8cb48a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'is_deleted')
    # ### end Alembic commands ###
