"""Add geographical info to user_profiles

Revision ID: 201acb1cdc8d
Revises: 5a3ac3b7c0ff
Create Date: 2026-03-29 17:11:13.547882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '201acb1cdc8d'
down_revision = '5a3ac3b7c0ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('user_profiles', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('municipality', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('address_complement', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'address_complement')
    op.drop_column('user_profiles', 'municipality')
    op.drop_column('user_profiles', 'department')
    op.drop_column('user_profiles', 'country')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B613EAB2A3B'))
    )
    # ### end Alembic commands ###
