"""Add geographical info to user_profiles

Revision ID: 201acb1cdc8d
Revises: 5a3ac3b7c0ff
Create Date: 2026-03-29 17:11:13.547882

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '201acb1cdc8d'
down_revision = '5a3ac3b7c0ff'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    """Check if a table exists in the current database."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES "
            "WHERE TABLE_NAME = :tbl"
        ),
        {"tbl": table_name},
    )
    return result.scalar() > 0


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS "
            "WHERE TABLE_NAME = :tbl AND COLUMN_NAME = :col"
        ),
        {"tbl": table_name, "col": column_name},
    )
    return result.scalar() > 0


def upgrade() -> None:
    # sysdiagrams is a SSMS system table — only drop if it actually exists
    if _table_exists("sysdiagrams"):
        op.drop_table("sysdiagrams")

    for col_name, col_type in [
        ("country", sa.String(length=100)),
        ("department", sa.String(length=100)),
        ("municipality", sa.String(length=100)),
        ("address_complement", sa.String(length=255)),
    ]:
        if not _column_exists("user_profiles", col_name):
            op.add_column("user_profiles", sa.Column(col_name, col_type, nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'address_complement')
    op.drop_column('user_profiles', 'municipality')
    op.drop_column('user_profiles', 'department')
    op.drop_column('user_profiles', 'country')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B613EAB2A3B'))
    )
    # ### end Alembic commands ###
