"""Add DTE fields to UserProfile

Revision ID: 2d2a5d54df8d
Revises: 5797ef78ebc7
Create Date: 2026-04-23 10:41:57.722456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '2d2a5d54df8d'
down_revision = '5797ef78ebc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('user_profiles', sa.Column('person_type', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('nrc', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('dui', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('nit', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('economic_activity', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('taxpayer_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'taxpayer_type')
    op.drop_column('user_profiles', 'economic_activity')
    op.drop_column('user_profiles', 'nit')
    op.drop_column('user_profiles', 'dui')
    op.drop_column('user_profiles', 'nrc')
    op.drop_column('user_profiles', 'person_type')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B610BE89209'))
    )
    # ### end Alembic commands ###
