"""Restore v4 to casbin_rule

Revision ID: 405d80422e8e
Revises: 16816d5fcbf5
Create Date: 2026-03-22 14:10:54.206538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405d80422e8e'
down_revision = '16816d5fcbf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casbin_rule', sa.Column('v4', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casbin_rule', 'v4')
    # ### end Alembic commands ###
