"""add_performance_indexes

Revision ID: 4f282f63dc37
Revises: b960f8551f4c
Create Date: 2026-06-12 23:34:43.795406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '4f282f63dc37'
down_revision = 'b960f8551f4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    
    # Drop existing index and recreate under SQLAlchemy naming convention
    op.drop_index('IX_incidental_charges_reservation_id', table_name='incidental_charges')
    op.create_index(op.f('ix_incidental_charges_reservation_id'), 'incidental_charges', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_incidental_charges_payment_status'), 'incidental_charges', ['payment_status'], unique=False)
    
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    
    op.create_index(op.f('ix_reservations_check_in'), 'reservations', ['check_in'], unique=False)
    op.create_index(op.f('ix_reservations_check_out'), 'reservations', ['check_out'], unique=False)
    op.create_index(op.f('ix_reservations_room_id'), 'reservations', ['room_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_room_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_out'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_check_in'), table_name='reservations')
    
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    
    op.drop_index(op.f('ix_incidental_charges_payment_status'), table_name='incidental_charges')
    op.drop_index(op.f('ix_incidental_charges_reservation_id'), table_name='incidental_charges')
    op.create_index('IX_incidental_charges_reservation_id', 'incidental_charges', ['reservation_id'], unique=False)
    
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    # ### end Alembic commands ###
