"""Add soft delete to rooms and room types

Revision ID: 5965ef8cb48a
Revises: 3b0a559c8f40
Create Date: 2026-03-23 19:18:16.871446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5965ef8cb48a'
down_revision = '3b0a559c8f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_types', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('rooms', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_deleted')
    op.drop_column('room_types', 'is_deleted')
    # ### end Alembic commands ###
