"""Add tax columns to reservation

Revision ID: 8173a12b6d59
Revises: d817c83cbad6
Create Date: 2026-04-27 15:34:58.992103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '8173a12b6d59'
down_revision = 'd817c83cbad6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.add_column('reservations', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reservations', sa.Column('tax_iva', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('reservations', sa.Column('tax_tourism', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'tax_tourism')
    op.drop_column('reservations', 'tax_iva')
    op.drop_column('reservations', 'subtotal')
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B61A75DA21D'))
    )
    # ### end Alembic commands ###
