"""Add season prices historic fields

Revision ID: d4cb2db6a2a3
Revises: 201acb1cdc8d
Create Date: 2026-04-15 16:55:29.939946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd4cb2db6a2a3'
down_revision = '201acb1cdc8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('season_prices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('season_prices', sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('season_prices', sa.Column('snapshot_base_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('season_prices', 'snapshot_base_price')
    op.drop_column('season_prices', 'is_archived')
    op.drop_column('season_prices', 'created_at')
    # ### end Alembic commands ###
