"""Add document_type

Revision ID: d817c83cbad6
Revises: 2d2a5d54df8d
Create Date: 2026-04-23 14:11:04.663237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'd817c83cbad6'
down_revision = '2d2a5d54df8d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('user_profiles', sa.Column('document_number', sa.String(length=50), nullable=True))
    
    # Data migration: transfer existing DUIs
    op.execute("UPDATE user_profiles SET document_type = 'DUI', document_number = dui WHERE dui IS NOT NULL")
    
    op.drop_column('user_profiles', 'dui')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('dui', sa.VARCHAR(length=20, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    
    # Reverse data migration
    op.execute("UPDATE user_profiles SET dui = document_number WHERE document_type = 'DUI'")
    
    op.drop_column('user_profiles', 'document_number')
    op.drop_column('user_profiles', 'document_type')
    # ### end Alembic commands ###
