"""Add payment_method and receipt_url

Revision ID: fc401d39b254
Revises: 8173a12b6d59
Create Date: 2026-05-01 09:48:10.728850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'fc401d39b254'
down_revision = '8173a12b6d59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_url', sa.String(length=500), nullable=True))
    op.add_column('reservations', sa.Column('payment_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'payment_method')
    op.drop_column('payments', 'receipt_url')
    # ### end Alembic commands ###
